baseurl = "http://gammenion.github.io/br/"
disablePathToLower = true
languageCode = "pt-br"
theme = "hugo-theme-bleak"
title = "Segurança das Coisas"
description = "Isso e aquilo sobre assuntos de segurança"
contentdir = "content.br"
publishdir = "public/br"
[Permalinks]
	post = "post/:filename"

canonifyurls = true

paginate = 6

[Params]
	logo = "/img/logo.jpg"
	# cover = "/img/06.png"
	twitter = "gammenion"
	github = "gammenion"
	Subtitle = "Isso e aquilo sobre assuntos de segurança"
	comments = true
	disqus = "disqus_QBNiJaWTUH"
	translationtitle = "Open in English"
	translationurl = "/"
	translationflag = "/img/usa.png"
	tags = [
		"Security",
		"Check Point",
        "Hardening",
        "SSH",
        "Github"
	]
