baseurl = "http://gammenion.github.io/"
disablePathToLower = true
languageCode = "en-us"
theme = "hugo-theme-bleak"
title = "Security of Things"
description = "This and that about security related matters"


canonifyurls = true

paginate = 6


[Params]
	logo = "/img/logo.jpg"
	# cover = "/img/background.png"
	twitter = "gammenion"
	github = "gammenion"
	Subtitle = "This and that about security related matters"
	comments = true
	disqus = "disqus_QBNiJaWTUH"
	translationtitle = "Abrir em Português"
	translationurl = "/br/"
	translationflag = "/img/brazil.jpg"
	tags = [
		"Security",
		"Check Point",
        "Hardening",
        "SSH",
        "Github"
	]
